### ISSUE TITLE
E: -30 / no version information available

### ISSUE THREAD

**Issue by bg-rad** [Oblomov/clinfo#10]
Hello, 

I seem to have some trouble with the location of the devices pertaining to OpenCL. I have the nvidia 340 drivers installed (with the belonging nvidia-opencl-icd-340 package) As soon as I run the program I simply get the E: -30 message. If I then forcefully install nvidia-libopencl1-340, it removes the ocl-icd-libopencl1 dependancy package, and then when I run the program I get the following output:

 clinfo: /usr/lib/i386-linux-gnu/libOpenCL.so.1: no version information available (required by clinfo)
E: -30

In any case it does not seem to find anything. If I locate all the packages using locate -i libOpenCL I get the following:

/usr/lib/i386-linux-gnu/libOpenCL.so
/usr/lib/i386-linux-gnu/libOpenCL.so.1
/usr/lib/i386-linux-gnu/libOpenCL.so.1.0.0
/usr/share/doc/ocl-icd-libopencl1
/usr/share/doc-base/ocl-icd-libopencl1
/usr/share/lintian/overrides/ocl-icd-libopencl1
/usr/share/man/man7/libOpenCL.7.gz
/usr/share/man/man7/libOpenCL.so.7.gz
/var/cache/apt/archives/nvidia-libopencl1-304-updates_304.125-0ubuntu0.0.1_i386.deb
/var/cache/apt/archives/nvidia-libopencl1-304_304.125-0ubuntu0.0.1_i386.deb
/var/cache/apt/archives/nvidia-libopencl1-331-updates_331.113-0ubuntu0.0.4_i386.deb
/var/cache/apt/archives/nvidia-libopencl1-340_340.76-100ubuntu100~ppa0~trusty_i386.deb
/var/cache/apt/archives/nvidia-libopencl1-346_346.47-100ubuntu100~ppa0~trusty_i386.deb
/var/cache/apt/archives/ocl-icd-libopencl1_2.1.3-4_i386.deb
/var/lib/doc-base/documents/ocl-icd-libopencl1
/var/lib/dpkg/info/nvidia-libopencl1-340.list
/var/lib/dpkg/info/nvidia-libopencl1-340.postrm
/var/lib/dpkg/info/ocl-icd-libopencl1:i386.list
/var/lib/dpkg/info/ocl-icd-libopencl1:i386.md5sums
/var/lib/dpkg/info/ocl-icd-libopencl1:i386.postinst
/var/lib/dpkg/info/ocl-icd-libopencl1:i386.postrm
/var/lib/dpkg/info/ocl-icd-libopencl1:i386.shlibs
/var/lib/dpkg/info/ocl-icd-libopencl1:i386.symbols

I am using the Ubuntu trusty the 32bit version and the 3.16.0-031600-generic kernel.
The gfx card is the the Nvidia GeForce 310.

**Comment by Oblomov** [comment]
From the error that you get I'm guessing that you are not running _this_ `clinfo`, but the one shipped with your version of Ubuntu, that has nothing to do with mine.

The `clinfo` in Ubuntu does not properly supports devices that only support OpenCL 1.1 (e.g. the nvidia ones), and it generally handles errors in a very non-robust way, but there's nothing I can do about it, sorry, it's a different program.

**Comment by magnumripper** [comment]
How would one go about lobbying for this clinfo being used instead? I presume their current one is AMD's? Surely they (be it Debian or Ubuntu) should prefer an open source project.

**Comment by bg-rad** [comment]
Yeah I'm sorry, for some reason I thought that this was the goto program included in the Ubuntu packages. In any case the output using your program is the following:

Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 1.1 CUDA 6.5.45
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts 
  Platform Extensions function suffix             NV

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     GeForce 310
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 1.0 CUDA
  Driver Version                                  340.76
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Topology (NV)                            PCI-E, 01:00.0
  Max compute units                               2
  Max clock frequency                             1402MHz
  Compute Capability (NV)                         1.2
  Max work item dimensions                        3
  Max work item sizes                             512x512x64
  Max work group size                             512
  Preferred work group size multiple              32
  Warp size (NV)                                  32
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               0 / 0        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              536084480 (511.2MiB)
  Error Correction support                        No
  Max memory allocation                           134217728 (128MiB)
  Unified memory for Host and Device              No
  Integrated memory (NV)                          No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       2048 bits (256 bytes)
  Global Memory cache type                        None
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max 2D image size                             4096x16383 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               16383 (16KiB)
  Registers per block (NV)                        16384
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     9
  Max size of kernel argument                     4352 (4.25KiB)
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Kernel execution timeout (NV)                 Yes
  Concurrent copy and kernel execution (NV)       Yes
    Number of async copy engines                  1
  Device Available                                Yes
  Compiler Available                              Yes
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts  cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  NVIDIA CUDA
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [NV]
  clCreateContext(NULL, ...) [default]            Success [NV]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.1.3
  ICD loader Profile                              OpenCL 1.2

The main part which bothers me being:

  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

do you by any chance know what could be wrong as to why it does not detect any devices/platforms ?

**Comment by Oblomov** [comment]
@magnumripper : the clinfo used in Debian/Ubuntu until now was developed by SImon RIchter. My understanding is that it will be replaced by mine, but I'm not sure about the timeline (I've been busy with other stuff and I have to refresh my contacts with the Debian OpenCL Maintainers).

@bg-rad : it does find platforms and devices (the NVIDIA one), otherwise you wouldn't see that huge listing. The part you are worried about is the fact that specifying NULL as platform will not actually pick a platform. This depends on the OpenCL ICD loader used, and it just means that a platform has to be specifically chosen by the application, nothing else and nothing to worry about.

**Comment by UniqueFool** [comment]
Just for your info, I can confirm that your clinfo code works properly on Ubuntu, while the stock version would trigger all sorts of errors/segfaults, especially with multiple ICDs  installed (nvidia, intel and AMD here), so it is good to see a piece of software that is apparently tested with all those use cases in mind.

Thanks for working on this, and best of luck to you for getting it included in Ubuntu !!

**Comment by Oblomov** [comment]
Thanks @UniqueFool —Debian has already adopted it for the next release, so Ubuntu will probably follow suite 8-)

**Comment by UniqueFool** [comment]
Given that there are at least ~15 different clinfo projects just on github, I would strongly suggest to add your nickname to the version string, to ensure that people can tell that they are running your version of clinfo - maybe even adding a link to the github project would be a good idea ?
