### ISSUE TITLE
Ubuntu Package Manager Update Needed

### ISSUE THREAD

**Issue by robertandrewsmith** [Oblomov/clinfo#12]
The current version is unavailable on Ubuntu Package Manager.
Please submit your update to Ubuntu Package Manager.

**Comment by Oblomov** [comment]
Distribution packaging of the program is not up to me, but to the respecting distributions and their maintainers. Please contact the `clinfo` package maintainer at Ubuntu and ask them to update.

**Comment by robertandrewsmith** [comment]
Do you keep a list of clinfo package maintainers for the respective distributions?
Who must I contact for Ubuntu 15.04?   I would be glad to contact them on your behalf.
Thanks.

**Comment by Oblomov** [comment]
You can find all relevant information for the clinfo package on Ubuntu [here](http://packages.ubuntu.com/vivid/clinfo). Please also note that by the look of it the `clinfo` packaged in Ubuntu is not this one.
