### ISSUE TITLE
Tags missing in repository.

### ISSUE THREAD

**Issue by woutershep** [Oblomov/clinfo#15]
Hi,

If i look at the history and at new-version.sh it seems that the commits of 'Version ...' are supposed to be tagged. However these tags don't seem to be published here on github anymore for a while now.
https://github.com/Oblomov/clinfo/tags

Perhaps you forgot that git doesn't push tags along by default?
https://git-scm.com/book/en/v2/Git-Basics-Tagging#Sharing-Tags

If this is actually on purpose though feel free to just close this bug report. I just thought i'd let you know.

**Comment by Oblomov** [comment]
You're right, I forgot to push the tags. Fixed now ;-)
