### ISSUE TITLE
Public Domain isn't a license

### ISSUE THREAD

**Issue by rossburton** [Oblomov/clinfo#16]
Public Domain isn't really a license - it doesn't say anything about the future, and other people's use, and in some countries the concept of PD doesn't really exist.

Would you consider relicensing to something with a well understood legal basis but still very permissive, such as two-clause BSD / MIT / etc?

**Comment by Oblomov** [comment]
I started thinking about this when I came across a relevant link on reddit. I've been thinking about switching to the CC0 (Creative Commons Zero) license (as an alternative, the WTFPL would be possibly less “serious” alternative).

**Comment by Oblomov** [comment]
OK, it's CC0 now, which seems to be the closest formally legal thing to public domain.

**Comment by rossburton** [comment]
👍
