### ISSUE TITLE
CMake support?

### ISSUE THREAD

**Issue by samatjain** [Oblomov/clinfo#20]
Hello! I noticed you've been adding more support for Windows. Did you have any desire to move to a cross-platform build system like CMake?

I have such a ~~branch~~ fork with most of the work done here: https://github.com/samatjain/clinfo

It builds on Visual Studio 2016 and Ubuntu 16.10 without issue. Missing from that ~~branch~~ fork is support for CMake's install targets, which would install the clinfo binary and man page into the right place on Linux.

**Comment by Oblomov** [comment]
Hello, and thanks for your work.

However, I feel that depending on CMake for such a simple program is a bit overkill. I would rather have the binary build out of the box without requiring any other dependency than the OpenCL development file and whatever build system the environment provides.

This is why i split my Unix Makefiles, allowing building with both BSD and GNU make, and why I wrote a simple NMAKE Makefile to build under Windows. I understand that there are limitations to this approach (for example, the Windows OPENCLDIR detection logic is not very sophisticated), but I would rather work around them as the need arises (for example, improving the OPENCLDIR detection logic by looking into the places where the Intel OpenCL SDK installs itself) than depend on a full-blow external build system.

So I'm afraid I will not merge your CMake support in, at least for the time being. If things start getting too complex, I might reconsider my choice though.
