### ISSUE TITLE
clinfo fails but beignet utests work

### ISSUE THREAD

**Issue by juanitotc** [Oblomov/clinfo#24]
Using clinfo from git as of today with a linux 64-bit system (linux-4.8.17 llvm-4.0.1 mesa-17.2.0) fails:

$ clinfo
: CommandLine Error: Option 'enable-value-profiling' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

..but opencl seems to be working from the beignet tests:

$ ./utest_run

platform number 1
platform_profile "FULL_PROFILE"
platform_name "Intel Gen OCL Driver"
platform_vendor "Intel"
platform_version "OpenCL 2.0 beignet 1.4 (git-afd050f)"
platform_extensions "cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_intel_media_block_io cl_intel_planar_yuv cl_khr_gl_sharing"
device_profile "FULL_PROFILE"
device_name "Intel(R) HD Graphics Haswell Ultrabook GT2 Mobile"
device_vendor "Intel"
device_version "OpenCL 1.2 beignet 1.4 (git-afd050f)"
device_extensions "cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_intel_media_block_io cl_intel_planar_yuv cl_khr_gl_sharing"
device_opencl_c_version "OpenCL C 1.2 beignet 1.4 (git-afd050f)"
27 image formats are supported
[CL_R CL_UNORM_INT8]
...

**Comment by juanitotc** [comment]
Ah - sorry for the noise..

$ sudo rm /etc/OpenCL/vendors/mesa.icd
[re-start X]
$ clinfo
Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.4 (git-afd050f)
  Platform Profile                                FULL_PROFILE
...

**Comment by Oblomov** [comment]
Yes, this is [a known issue with LLVM 3.9 and later](https://bugs.llvm.org/show_bug.cgi?id=30587) which essentially prevents multiple ICDs with that dynamically load the Clang library to coexist, even when the library version used is the same.
