### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by candrews** [Oblomov/clinfo#27]
Can you please make a new release?

It would make life much easier if there was a release including https://github.com/Oblomov/clinfo/commit/f98c9ede8e06ca52b7c86c4c9a320e00c66d22ab

Thanks!

(BTW, I'm packaging this for Gentoo, it's be in Portage at dev-util/clinfo soon)

**Comment by Oblomov** [comment]
Pushed tag 2.2.17.10.25, and thanks for the gentoo package.
