### ISSUE TITLE
CL_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT check for doubles

### ISSUE THREAD

**Issue by franz** [Oblomov/clinfo#28]
clinfo checks both CL_DEVICE_SINGLE_FP_CONFIG and CL_DEVICE_DOUBLE_FP_CONFIG for CL_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT, and shows "No" for DOUBLE_FP_CONFIG.

Which is a bug because that flag is not present in DOUBLE_FP_CONFIG (correctly rounded sqrt/div is mandatory by spec for doubles)

**Comment by Oblomov** [comment]
This should be fixed in 2749190444945fadc6c86fe0e93108beff5748d6
