### ISSUE TITLE
Suggest about clGetPlatformIDs and clGetDeviceIDs

### ISSUE THREAD

**Issue by sgqy** [Oblomov/clinfo#30]
I am using ARM Platform with Mali-T760 GPU. The system is lubuntu 14.04. 
OpenCL works well on it, but sometimes it suddenly not work, `clGetPlatformIDs` returns 
 `CL_PLATFORM_NOT_FOUND_KHR`.
After some tries, I got the tips:

* Link against the libraries from the GPU manufacture directly, instead of libOpenCL.
* Re-linking libOpenCL to the manufacture version may solve this problem.
* Some packages may break the driver stack, sadly it may be better to reinstall the system.

------
About `clGetDeviceIDs`. On my platform, it returns `CL_OUT_OF_HOST_MEMORY (-6)`, when:
* Kernel driver is not loaded properly.
* User driver is not match with kernel driver.
* Permission denied when access GPU node, such as `/dev/mali0`.
  `chmod` works on this problem.
* Really no enough memory (rarely).

**Comment by Oblomov** [comment]
While I appreciate the comments, I don't think it's the role of `clinfo` to try and detect why and how a system is misconfigured.
