### ISSUE TITLE
fatal error: CL/cl.h: No such file or directory

### ISSUE THREAD

**Issue by candrews** [Oblomov/clinfo#36]
Compiling clinfo (version 1.1.0) results in this failure:
```
make -j2
cc -march=native -O2 -pipe -std=c99 -Wall -Wextra   -c -o clinfo.o src/clinfo.c
In file included from src/error.h:5:0,
                 from src/clinfo.c:31:
src/ext.h:24:10: fatal error: CL/cl.h: No such file or directory
 #include <CL/cl.h>
          ^~~~~~~~~
compilation terminated.
```

However, cl.h does exist. Here are the paths to files with this name:
```
/usr/lib64/OpenCL/global/include/CL-1.0/cl.h
/usr/lib64/OpenCL/global/include/CL-1.1/cl.h
/usr/lib64/OpenCL/global/include/CL-1.2/cl.h
/usr/lib64/OpenCL/global/include/CL-2.0/cl.h
/usr/lib64/OpenCL/global/include/CL-2.1/cl.h
(/usr/include/CL/cl.h (symlink to /usr/lib64/OpenCL/global/include/CL-1.2/cl.h)
```

I believe that the last one, `/usr/include/CL/cl.h`, is what should be found and used.

Can you please take a look?

Originally reported at https://bugs.gentoo.org/660572

**Comment by Oblomov** [comment]
Hello, and thanks for the report.

I'm afraid this is either a distribution-specific packaging issue, or something got hosed in the setup of the original submitter, I'm not sure what I can do about it from here.

Can you please ask the original submitter to double-check that the headers are actually accessible? Some as simple as `head -n2 /usr/include/CL/cl.h` should do it.

**Comment by Oblomov** [comment]
OK, from the follow-up of the original submitter on the Gentoo bugtracker, it seems that the issue was fixed by reinstalling, supporting the idea of something misconfigured on the user machine. I'm closing this issue now, but feel free to reopen if further information becomes available.
