### ISSUE TITLE
Better way to do the multiarch switching in Makefile.win

### ISSUE THREAD

**Issue by LeMoussel** [Oblomov/clinfo#37]
To do a better way to do the multiarch switching, in `Makefile.win `, you can do :
```
!IF "$(PROCESSOR_ARCHITEW6432)" == "AMD64"
ARCH=64
!ELSE IF "$(PROCESSOR_ARCHITECTURE)" == "IA64" || "$(PROCESSOR_ARCHITEW6432)" == "AMD64"
ARCH=64
!ELSE IF "$(PROCESSOR_ARCHITECTURE)" == "x86"
ARCH=32
!ENDIF
```

**Comment by Oblomov** [comment]
My understanding is that `PROCESSOR_ARCHITECTURE` is set to match the current development environment, whereas `PROCESSOR_ARCHITEW6432` is set to the machine's own architecture, so I don't think we should use the latter in the switch, can you confirm?

**Comment by LeMoussel** [comment]
If you’re on 64-bit Windows, you’ll see that you have a PROCESSOR_ARCHITECTURE environment variable:
> C:\>echo %PROCESSOR_ARCHITECTURE%
> AMD64
This is from a 64-bit Command Prompt on 64-bit Windows.

If you run the 32-bit (x86) Command Prompt, you’ll see something different:
> C:\>echo %PROCESSOR_ARCHITECTURE%
> x86
> 
> C:\>echo %PROCESSOR_ARCHITEW6432%
> AMD64

Most reliable solution:

> set Arch=x64
> if "%PROCESSOR_ARCHITECTURE%" == "x86" ( 
>     if not defined PROCESSOR_ARCHITEW6432 set Arch=x86
> )

**Comment by Oblomov** [comment]
My point is that if you're launching the build from the 32-bit command prompt, it makes sense to build a 32-bit executable, even if the Windows installation is a 64-bit one. If you want to build a 64-bit executable, launch the build itself from a 64-bit command prompt (or other 64-bit environment). So it makes sense to switch based on `%PROCESSOR_ARCHITECTURE%`.
