### ISSUE TITLE
Out-of-Bounds access in device_info_interop_list

### ISSUE THREAD

**Issue by ltowarek** [Oblomov/clinfo#38]
Hi. It seems that there is an out-of-bounds access in `device_info_interop_list`. The issue occurs when processing `CL_DEVICE_SIMULTANEOUS_INTEROPS_INTEL`.

In [this line](https://github.com/Oblomov/clinfo/blob/master/src/clinfo.c#L2056) `i` is set to `76`, because `current = 0x4072 = CL_CONTEXT_D3D9EX_DEVICE_INTEL` and `n->from = 0x4026 = CL_CONTEXT_D3D9_DEVICE_INTEL`. Length of `n->value` is `5`, so `n->value[76]` ends with the access violation in the `snprintf`.

I can reproduce this issue using Intel Graphics Driver for Windows 10 [25.20.100.6323](https://downloadcenter.intel.com/download/28180/Intel-Graphics-Driver-for-Windows-10).

**Comment by Oblomov** [comment]
Thanks for looking into the issue this thoroughly. I pushed 9d3f66f that should fix this issue. Can you verify?

**Comment by ltowarek** [comment]
Now it works as expected. Thank you!

**Comment by Oblomov** [comment]
Thanks for reporting back, I'm closing the issue now.
