### ISSUE TITLE
AMD GPUs remain in power state 3 after exiting clinfo.

### ISSUE THREAD

**Issue by Bengt** [Oblomov/clinfo#43]
Hi,

I noticed that running clinfo on Vega 10 GPUs makes the remain in the power state 3 (4 LEDs active in GPUTach). The only reliable workaround seems to be rebooting the system.

This issue has been reported for TensorFlow-ROCm here:

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/621

It has also been reported for ROCm itself here:

https://github.com/RadeonOpenCompute/ROCm/issues/857

Some GPU-using applications trigger this behaviour (like TensorFlow-ROCm and clinfo) and some don't (most 3D games, for example). Do you maybe have an idea on how to avoid this behaviour on the application level?

Regards,
Bengt

**Comment by Oblomov** [comment]
Interesting issue, but this is definitely something which is hardware and/or firmware related, there isn't much applications can do about it other than cleaning up properly, which `clinfo` already does (there's a `clRelease` for every `clCreate`).

**Comment by Bengt** [comment]
Thanks for giving this some thought. Interesting that clinfo triggers this bug, although it cleans up as well as that. Hopefully this can help debugging the core issue in the driver.

**Comment by Oblomov** [comment]
No problem. Following the comment threads it seems this is related specifically to compute contexts, which probably follow a different driver/firmware codepath than graphics contexts —with the latter doing cleanups that the former does not, maybe?
