### ISSUE TITLE
clinfo[1]: syntax error: unexpected '('

### ISSUE THREAD

**Issue by dongjinxin123** [Oblomov/clinfo#44]
Hi I build the clinfo on my Mac and push the executable to my Android device /system/bin using adb. 
I run it use ./clinfo

the terminal shows :          clinfo[1]: syntax error: unexpected '('

could you please give me some hint?

**Comment by Oblomov** [comment]
I honestly have no idea, I never tried such a setup.

**Comment by Oblomov** [comment]
The only thing I can think of is that the clinfo on the Mac was compiled for the Mac's own architecture rather than cross-compiled for the Android architecture, so it won't be able to run on Android anyway. Check out issue #46 for hints on how to do an Android build directly on Android.

**Comment by Oblomov** [comment]
I'm going to close this issue. Feel free to reopen with additional information if needed.
