### ISSUE TITLE
Segmentation fault with rocm 3.3

### ISSUE THREAD

**Issue by xcom169** [Oblomov/clinfo#47]
Segmentation fault with rocm 3.3 on Manjaro Linux.

**Comment by Oblomov** [comment]
Can you please run under gdb and provide a stack trace?

**Comment by xcom169** [comment]
Sure:

`[]# gdb clinfo
GNU gdb (GDB) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from clinfo...
(No debugging symbols found in clinfo)
(gdb) run clinfo
Starting program: /usr/bin/clinfo clinfo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
ignoring unknown command-line parameter clinfo
[New Thread 0x7ffff76d2700 (LWP 84689)]

Thread 1 "clinfo" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e49460 in free () from /usr/lib/libc.so.6
(gdb) 

`

**Comment by xcom169** [comment]
Maybe it's related: https://github.com/RadeonOpenCompute/ROCm/issues/1091

**Comment by Oblomov** [comment]
I don't think it's related to tht issue, even though it's likely the issue is actually within ROCm. Can you please provide the backtrace after the SIGSEGV? (`bt full` command in gdb)

**Comment by xcom169** [comment]
As of today it's working again.
Strange. 

Thanks!

**Comment by Oblomov** [comment]
I love bugs that fix themselves (I'm guessing the issue was in some library or kernel driver that got upgraded in the mean time).
