### ISSUE TITLE
Compilation error with the Intel headers

### ISSUE THREAD

**Issue by andpic** [Oblomov/clinfo#48]
When I compile _clinfo_ with the Intel 2.0 headers I get the following error:
```
cc -g -pedantic -Werror -std=c99 -Wall -Wextra -I../OpenCL-Headers  -c -o clinfo.o src/clinfo.c
src/clinfo.c:2378:23: error: ‘CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS’ undeclared here (not in a function); did you mean ‘CL_DEVICE_SUBGROUP_INDEPENDENT_FORWARD_PROGRESS’?
  { CLINFO_BOTH, DINFO(CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS, INDENT "Sub-group independent forward progress", bool), dev_is_21 },
                       ^
src/clinfo.c:2164:34: note: in definition of macro ‘DINFO’
 #define DINFO(symbol, name, typ) symbol, #symbol, name, NULL, device_info_##typ
                                  ^~~~~~
<builtin>: recipe for target 'clinfo.o' failed
make: *** [clinfo.o] Error 1
```

**Comment by andpic** [comment]
Changing `CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS` to `CL_DEVICE_SUBGROUP_INDEPENDENT_FORWARD_PROGRESS` works on my machine.

**Comment by Oblomov** [comment]
Thanks for the report, but this is an issue with the SDK you are using, not in `clinfo`. [The official name for the define is `CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS`](https://github.com/KhronosGroup/OpenCL-Headers/blob/v2020.03.13/CL/cl.h#L389).

I could work around this in `clinfo`, but any software developed on those headers is likely to fail when compiled with the official ones.

I recommend reporting your issue to the SDK upstream (or check if there is a more recent version available —the Intel headers I have here use the correct name).

**Comment by andpic** [comment]
Thank you for answering! I'll upgrade the SDK and check if they fixed that.
