### ISSUE TITLE
OpenCL 3.0 preliminary support?

### ISSUE THREAD

**Issue by oscarbg** [Oblomov/clinfo#50]
Hi,
I say now because seems latest Intel Neo driver has started supporting OpenCL 3.0 yet on unreleased HW:
https://github.com/intel/compute-runtime/releases/tag/20.22.16952
also we have OpenCL loader 3.0 support:
https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/23475bd123d43d2087323962344457fe4a0fb13c

**Comment by Oblomov** [comment]
Thanks for the heads-up about the Neo driver. I've been thinking about adding support for OpenCL 3.0 since the first draft came out, but it's considerably more work, so I'll need some time to design this properly.

**Comment by anbe42** [comment]
There was a bugfix committed recently that works around the misleading
```
        NOTE:   your OpenCL library declares to support OpenCL 3.0,
                but it seems to support up to OpenCL 2.2 only.
```
A real fix to prevent this from reappearing with the next new standard would be to cap this version check at the last version `clinfo` knows about and emit a different notice if any loader or ICD claims to support something newer.
(Claiming to support 4.0 while missing 2.2 symbols obviously should still be an error.)

Andreas

**Comment by Oblomov** [comment]
I had a similar thought recently. I've pushed a new patch that should future-proof clinfo against those warnings in case the loader is more recent than clinfo.

Please open a separate issue next time, though.

**Comment by Oblomov** [comment]
FWIW, I've started implementing OpenCL 3 support internally. The Intel NEO driver for their GPUs supports it, which means I can actually test it. I've already hit a snag in that Debian recently updated their OpenCL headers to include 3.0 support, _and_ it's already an obsolete version missing some of the more recent defines and data type ;-)

I'm not sure if I'll make a release before things settle down, or at least v3 of the standard is officially finalized.

**Comment by anbe42** [comment]
I assume you used the packaged headers from May. I updated `khronos-opencl-headers` in Debian this week to Khronos' git repository contents as of 2020.10.14 (9fac4e9) - does that include the missing bits?

**Comment by Oblomov** [comment]
Oh, LOL, I knew I should have double-checked this morning for updates! Yeah, they seem to be in sync now.

I've pushed a provisional-30 branch with provisional 3.0 support in the mean time, for those that want to test it.

**Comment by Oblomov** [comment]
Wait, OpenCL 3.0 final has been released, no need for provisional branches.

OK, merged in master, tagged and pushed.
