### ISSUE TITLE
False positives in extensions detection

### ISSUE THREAD

**Issue by pierremoreau** [Oblomov/clinfo#52]
The current code checking for extensions looks for the extension name being a substring in the whole extension list string (see the [code](https://github.com/Oblomov/clinfo/blob/c83e67453a31df0dbd8a5091fd1034752b5d93bf/src/clinfo.c#L913)).

However this can return false positives, for example if _cl_khr_spirv_no_integer_wrap_decoration_ is exposed but _cl_khr_spir_ is not, _clinfo_ will falsely find out that _cl_khr_spir_ is advertised due to finding that substring as it does not check that the substring is followed by a space or a null character.

**Comment by Oblomov** [comment]
Nice catch!

I believe this should be fixed in the latest commit I just pushed (f5bda675e7), but feel free to reopen if this is not the case.

**Comment by pierremoreau** [comment]
It is indeed fixed with the latest version, thank you!
(I apparently complitely missed the notification for this issue, sorry about that.)
