### ISSUE TITLE
Uninitialised value cause print of random characters

### ISSUE THREAD

**Issue by anbe42** [Oblomov/clinfo#56]
I just received https://bugs.debian.org/975339 on 2.2.18.04.06 while updating the Debian package for todays 3.0 release. Is that perhaps already fixed?

There is also a typo in `man1/clinfo.1`: `s/successfull /successful /`

**Comment by Oblomov** [comment]
Hello,

I believe that bug was fixed by commit c83e67453a31df0dbd8a5091fd1034752b5d93bf, which is included in 3.0.20.11.20

Also thanks for pointing out the typo.
