### ISSUE TITLE
CL_DEVICE_OPENCL_C_ALL_VERSIONS is OpenCL 3 only-feature

### ISSUE THREAD

**Issue by doe300** [Oblomov/clinfo#59]
So unless I miss something, the [cl_khr_extended_versioning](https://github.com/KhronosGroup/OpenCL-Docs/blob/master/ext/cl_khr_extended_versioning.asciidoc) extension does not define `CL_DEVICE_OPENCL_C_ALL_VERSIONS`, but [OpenCL 3](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_DEVICE_OPENCL_C_ALL_VERSIONS) does, which would make the check in https://github.com/Oblomov/clinfo/blob/12c650f2be5270e33e1d1f8f63dd69ac7d36271e/src/clinfo.c#L2543 wrong.

**Comment by Oblomov** [comment]
Good point. Fixed and pushed.
