### ISSUE TITLE
Got error on android

### ISSUE THREAD

**Issue by Saikatsaha1996** [Oblomov/clinfo#60]
![Screenshot_20201213-133901](https://user-images.githubusercontent.com/72664192/102007339-358b5800-3d4e-11eb-9f77-eb36cd258582.png)
![Screenshot_20201213-141608](https://user-images.githubusercontent.com/72664192/102007341-37551b80-3d4e-11eb-8b10-35485345a612.png)
Please help me

**Comment by Oblomov** [comment]
I think you misinterpreted the instructions in the README. There is no need to to override `CPPFLAGS` if `OpenCL-Headers` was cloned next to `clinfo`. Also, the path should be the actual path.

**Comment by Saikatsaha1996** [comment]
Can you please guide me step by step?
Please...

**Comment by Oblomov** [comment]
Sorry, I'm afraid that I can't help you. I don't know what clpeak's APK does differently to find platforms that clinfo does not. It's possible they end up using different libOpenCL libraries. Since I do not have the same device as you, I cannot test to find a possible solution.

I'm reopening the issue, but you should edit the title and description providing more details about your hardware configuration (cellphone model, android version etc).

**Comment by Saikatsaha1996** [comment]
![Screenshot_20201214-002342](https://user-images.githubusercontent.com/72664192/102021032-fe936180-3da2-11eb-8944-406b60598100.png)
![Screenshot_20201214-002348](https://user-images.githubusercontent.com/72664192/102021034-005d2500-3da3-11eb-8b0e-12d954e29b8d.png)
![Screenshot_20201214-002414](https://user-images.githubusercontent.com/72664192/102021035-018e5200-3da3-11eb-9f30-5ad2ddbb36aa.png)
![Screenshot_20201214-002424](https://user-images.githubusercontent.com/72664192/102021038-0226e880-3da3-11eb-8fbd-0c4416e2da0a.png)
![Screenshot_20201214-002433](https://user-images.githubusercontent.com/72664192/102021039-02bf7f00-3da3-11eb-81ba-9699f3053379.png)
![Screenshot_20201214-002443](https://user-images.githubusercontent.com/72664192/102021040-03581580-3da3-11eb-8a4a-9f225a002009.png)
![Screenshot_20201214-002506](https://user-images.githubusercontent.com/72664192/102021041-03f0ac00-3da3-11eb-9485-5703d6cb9640.png)
![Screenshot_20201214-002451](https://user-images.githubusercontent.com/72664192/102021043-0521d900-3da3-11eb-9659-e83a8716392c.png)
![Screenshot_20201214-002514](https://user-images.githubusercontent.com/72664192/102021044-05ba6f80-3da3-11eb-8498-cb53a2299d62.png)
![Screenshot_20201214-002523](https://user-images.githubusercontent.com/72664192/102021045-06530600-3da3-11eb-9b9b-7a8891e84dd0.png)

**Comment by Oblomov** [comment]
Interesting that AIDA64 also identifies the OpenCL device. Can you try this in your `clinfo` directory:

    make clean && make ANDROID_VENDOR_PATH=/system/vendor/lib && ./clinfo

**Comment by Saikatsaha1996** [comment]
Ok i will trying...
Thank you 😊

**Comment by Saikatsaha1996** [comment]
![Screenshot_20201214-005623](https://user-images.githubusercontent.com/72664192/102021659-37353a00-3da7-11eb-9aa0-f9351adfa5e3.png)

**Comment by Oblomov** [comment]
Hm, there's something odd with that build output. Either you aren't on the latest version of `clinfo`'s `master` branch (you can check: what's the output of `git rev-parse HEAD`?) or your Android system is not being recognized as such. What's the output of `uname -a`?

**Comment by Saikatsaha1996** [comment]
How can i slove this?

**Comment by Oblomov** [comment]
Please provide the outputs of `git rev-parse HEAD` and `uname -a`.

**Comment by Saikatsaha1996** [comment]
![Screenshot_20201214-130913](https://user-images.githubusercontent.com/72664192/102053357-9d54a800-3e0d-11eb-941a-83b6a4fb2066.png)

**Comment by Oblomov** [comment]
I was asking for `git rev-parse HEAD` for `clinfo`, not for the OpenCL headers. Regardless, I have no idea what this `start-ubuntu.sh` is or does, the instructions for building on Android refer to the plain Termux environment. Additional layers are not a supported configuration.

**Comment by Saikatsaha1996** [comment]
![Screenshot_20201214-171518](https://user-images.githubusercontent.com/72664192/102077912-0baa6200-3e30-11eb-8b20-8cc06afb2c75.png)
Now make completed but when I put clinfo showing no commend found

**Comment by Saikatsaha1996** [comment]
![Screenshot_20201214-182224](https://user-images.githubusercontent.com/72664192/102083350-68f6e100-3e39-11eb-96fd-eac2de36aff5.png)
Thank you so much 🥰
I got it... thank you for your help

**Comment by Saikatsaha1996** [comment]
So now i can run any opencl application in my device? 🥰🥰

**Comment by Saikatsaha1996** [comment]
![Screenshot_20201214-182224](https://user-images.githubusercontent.com/72664192/102111172-0e22b100-3e5c-11eb-9365-fcce7890f976.png)
![Screenshot_20201214-195733](https://user-images.githubusercontent.com/72664192/102111184-10850b00-3e5c-11eb-9a48-e5066ba9ae6d.png)
After this same problem happen 
Failed to load OpenCL runtime

**Comment by Oblomov** [comment]
Sorry, take that up with the developers of the application you're trying to run.

**Comment by Saikatsaha1996** [comment]
But my android mobile capable with OpenCL i am right?

**Comment by Oblomov** [comment]
The cellphone is OpenCL-capable, but AIDA64 already confirmed that.
