### ISSUE TITLE
i915 not found

### ISSUE THREAD

**Issue by peepo** [Oblomov/clinfo#61]
cry for help:

ASUS C200M chromebook running ubuntu 18.04 aka GalliumOS 3.1

$ clinfo
Number of platforms                               0

evidence that opencl runs on Intel HD 400 aka i915:

HELP: i915 does not OpenCL(ing) anymore
https://community.intel.com/t5/OpenCL-for-CPU/HELP-i915-does-not-OpenCL-ing-anymore/td-p/1104442

$ lsmod | grep i915
i915                 1634304  25
i2c_algo_bit           16384  1 i915
drm_kms_helper        188416  1 i915
video                  45056  1 i915
drm                   446464  10 drm_kms_helper,i915

[modinfo_i915.txt](https://github.com/Oblomov/clinfo/files/6091684/modinfo_i915.txt)

00:02.0 VGA compatible controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0e) (prog-if 00 [VGA controller])
	Subsystem: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display
	Flags: bus master, fast devsel, latency 0, IRQ 89
	Memory at d0000000 (32-bit, non-prefetchable) [size=4M]
	Memory at c0000000 (32-bit, prefetchable) [size=256M]
	I/O ports at 1000 [size=8]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [d0] Power Management version 2
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [b0] Vendor Specific Information: Len=07 <?>
	Kernel driver in use: i915
	Kernel modules: i915

apologies, 
not clear to me what needs to be done

tx

**Comment by Oblomov** [comment]
I'm afraid that your issue has nothing to with clinfo. You'll need to install an OpenCL platform that supports your iGP, either Beignet or the new Intel compute runtime.

**Comment by peepo** [comment]
extremely kind!!

not listed as a dependency, by the application I installed

tx
