### ISSUE TITLE
checkNullBehavior using uninitialized error message

### ISSUE THREAD

**Issue by yshybeka** [Oblomov/clinfo#62]
https://github.com/Oblomov/clinfo/blob/d34bc1a3bdc148e2e1fe64998398e1a0552ab04c/src/clinfo.c#L3592

```
			ret.err = CL_DEVICE_NOT_FOUND;
			strbuf_append(__func__, &ret.str, "<error: no devices in non-default plaforms>");
```

This should append into `ret.err_str`

**Comment by Oblomov** [comment]
Thanks, this should be fixed in the latest commit.
