### ISSUE TITLE
Help wanted 

### ISSUE THREAD

**Issue by Saikatsaha1996** [Oblomov/clinfo#65]
I already installed Clinfo in direct termux.... And it's success...
But I really wanted to Help... Please help me 🙏🙏🙏🙏
I want to build Clinfo in TermuxArch under termux...
Can it possible ?..
Please help me... I really want help for this...

**Comment by Oblomov** [comment]
I do not know TermuxArch, but I would expect to work in pretty much the same way as plain Termux. You can probably follow the same instructions, just using the Arch package manager to install the relevant packages.

**Comment by Saikatsaha1996** [comment]
Useing same way but getting error..
L home/OpenCL-headers not found

**Comment by Oblomov** [comment]
I do not have the setup so I'm afraid I cannot help. I'm reopening the issue, in case somebody else can contribute.

**Comment by Saikatsaha1996** [comment]
> I do not have the setup so I'm afraid I cannot help. I'm reopening the issue, in case somebody else can contribute.

Okkk thank you I am waiting for solution...
🙏🙏🥰🥰

**Comment by Saikatsaha1996** [comment]
> I do not have the setup so I'm afraid I cannot help. I'm reopening the issue, in case somebody else can contribute.

Please see I am getting error like this
If you have any suggestions or solutions please inform me

![Screenshot_2021-05-27-23-45-46-117_com termux](https://user-images.githubusercontent.com/72664192/119876707-ca24f380-bf45-11eb-9600-eab6a9b3e47d.jpg)

**Comment by LightDestory** [comment]
With a friend we managed to compile openCL programs on a smartphone running Android and I can say: there is no a stardard way. For example my Samsung S9+ requires to make a copy of the internal libs because Android (Samsung Stock ROM) didn't allow the linking.

My friend with a different ROM had less issue. Check your phone and find the correct libs... then copy them into a tmp folder inside termux and add the path to the LD_LIBRARY_PATH

**Comment by Saikatsaha1996** [comment]
> With a friend we managed to compile openCL programs on a smartphone running Android and I can say: there is no a stardard way. For example my Samsung S9+ requires to make a copy of the internal libs because Android (Samsung Stock ROM) didn't allow the linking.
> 
> My friend with a different ROM had less issue. Check your phone and find the correct libs... then copy them into a tmp folder inside termux and add the path to the LD_LIBRARY_PATH

Under termux directly it not issue...
But when I installed under termux ubuntu I got problem..

**Comment by Saikatsaha1996** [comment]
> I do not have the setup so I'm afraid I cannot help. I'm reopening the issue, in case somebody else can contribute.

I got one solution but I am not clear
So help wanted
I got error like this
So I want to define one line 
" -ldl  don't need "
Can you tell me how can I define in command line as -ldl  dlsys@libic, dlclose@libc and etc I don't want...
![Screenshot_20210613-022131983](https://user-images.githubusercontent.com/72664192/121789071-690d4900-cbf0-11eb-8be0-cbc12b22ce4e.jpg)

**Comment by Oblomov** [comment]
This looks like an issue with the termux ubuntu linker. Since this is not related to clinfo itself, I recommend you report the issue to the developers of termux ubuntu. I'm closing this for the moment.

**Comment by Saikatsaha1996** [comment]
> This looks like an issue with the termux ubuntu linker. Since this is not related to clinfo itself, I recommend you report the issue to the developers of termux ubuntu. I'm closing this for the moment.

But I don't know how possible ..
But yesterday I got success with termux proot-distro
Ubuntu 20.04
Clinfo success..
And today I got same error..😭

**Comment by Saikatsaha1996** [comment]
Today I got error like this
I am really confusing
Fast we need to build OpenCL-Headers
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$PREFIX
cmake --build build --target install
After that
cd Clinfo
export LD_LIBRARY_PATH="/system/vendor/lib64:/system/lib64"
export CFLAGS="-I$HOME/OpenCL-Headers"
export LDFLAGS="-L/system/vendor/lib64"
make
I got success
But today same problem happen
😭😭😭

![Screenshot_2021-06-26-20-48-39-404_com termux](https://user-images.githubusercontent.com/72664192/123517660-e8eee500-d6bf-11eb-8f0d-4710fa062671.jpg)
