### ISSUE TITLE
Deleted AppVeyor artifact

### ISSUE THREAD

**Issue by temp254** [Oblomov/clinfo#66]
Hi,

It looks like it has been more than one month since the last AppVeyor job was launched, so the artifact has been deleted. More info at: https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy

Could you relaunch the job?
Thank you very much.

**Comment by Oblomov** [comment]
Done, but we seriously need a better way to handle this.

**Comment by temp254** [comment]
I agree completely. Thank you!
