### ISSUE TITLE
No support for staged installs

### ISSUE THREAD

**Issue by paulmenzel** [Oblomov/clinfo#70]
[Staged installs by using `DESTDIR`](https://www.gnu.org/software/make/manual/html_node/DESTDIR.html) is useful for package creation. It’d be great, if `make DESTDIR=/scratch/local2/` would be supported.

**Comment by Oblomov** [comment]
Thanks!

**Comment by paulmenzel** [comment]
Sorry, I was a few seconds too late pushing my fix.
