### ISSUE TITLE
clinfo hangs on configurations with two AMD GPU and open source rocm 

### ISSUE THREAD

**Issue by NTMan** [Oblomov/clinfo#81]
clinfo hangs in a cycle since it completely occupies one processor core. Same symptoms I observed when launch "DaVinci Resolve". On a desktop with a single Radeon 6900XT GPU, this problem does not occurs.

My configuration:
One GPU is internal in the RENOIR processor, and the other is a discrete AMD Radeon 6800M (It laptop ASUS G513QY)
In the BIOS there is no ability to turn off the integrated GPU in the processor, so there is no way to check this configuration with each GPU separately.

In the kernel log there is no error so it is most likely a user space issue, but I am not sure about it.

But when I forcibly terminate clinfo (press <Ctrl + C> until in the terminal returned typing) in the kernel log appears follow messages:
[ 1962.000909] amdgpu: HIQ MQD's queue_doorbell_id0 is not 0, Queue preemption time out
[ 1962.000912] amdgpu: Failed to evict process queues
[ 1962.000918] amdgpu: Failed to quiesce KFD
[ 1966.010395] amdgpu: HIQ MQD's queue_doorbell_id0 is not 0, Queue preemption time out
[ 1966.010406] amdgpu: Resetting wave fronts (cpsch) on dev 00000000b40e7982

I am used open source rocm stack from package rocm-opencl [[1](https://copr.fedorainfracloud.org/coprs/mystro256/rocm-opencl/)] which passed review and already pushed to official Fedora repository [[2](https://bugzilla.redhat.com/show_bug.cgi?id=2090823)].

Output clinfo ended with line:
```Max work group size (AMD)                       1024```
Full clinfo output you can find here [[3](https://pastebin.com/TR5zy30Z)]
Backtrace clinfo you can find here [[4](https://pastebin.com/wv5iGibi)]

Versions:
```
# rpm -qa | grep clinfo
clinfo-3.0.21.02.21-3.fc36.x86_64

# rpm -qa | grep rocm
rocm-comgr-5.2.0-1.fc37.x86_64
hsakmt-1.0.6-23.rocm5.2.0.fc37.x86_64
rocm-runtime-5.2.0-1.fc37.x86_64
rocm-opencl-5.2.0-1.fc37.x86_64
```

[1] https://copr.fedorainfracloud.org/coprs/mystro256/rocm-opencl/
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2090823
[3] https://pastebin.com/TR5zy30Z
[4] https://pastebin.com/wv5iGibi

**Comment by Oblomov** [comment]
Thanks for the report, but this is an issue in the rocm and/or kernel stack, there isn't much I can do on the clinfo side to fix it or work around it. The fact that it also happens in DaVinci Resolve confirms this. Please open a ticket with your distribution maintainers against the rocm-opencl package with this same information, they are in a better position to help solve the issue.
