### ISSUE TITLE
Links to both Windows Binaries are broken

### ISSUE THREAD

**Issue by samjfuller** [Oblomov/clinfo#88]
When clicking the link to either set of binaries, it comes up with a blank page stating "{"message":"Artifact not found or access denied."}"

I'm guessing this isn't supposed to happen?

**Comment by samjfuller** [comment]
Looks like the .exe is available here: https://github.com/ahoylabs/clinfo/releases/tag/master-d2baa06

**Comment by engineer1109** [comment]
My Windows Build. Same code with cmake.

Download:
https://github.com/engineer1109/clinfo/releases/tag/v1.0

**Comment by SatjaSivcev** [comment]
Voting to fix this

**Comment by Oblomov** [comment]
This is a duplicate of #45
