### ISSUE TITLE
cannot find -lOpenCL while compilation

### ISSUE THREAD

**Issue by iravikiran** [Oblomov/clinfo#96]
Hello, 

I'm trying to build the clinfo on my RISC-V Dev platform which has support with GPU. I've done all the setups as suggested in the ReadMe document, I've also successfully complied and installed OpenCL-Headers. But the issue that I'm facing right now is when I try to run `make` within the clinfo source repo I'm getting the below error and I'm unable to proceed. 

```
root@root:~/CL/clinfo# make
cc -g -pedantic -Werror -std=c99 -Wall -Wextra -I/home/root/CL/OpenCL-Headers/ocl/install -I../OpenCL-Headers   -o clinfo clinfo.o  -lOpenCL -ldl
/usr/lib/gcc/riscv64-oe-linux/10.1.0/../../../../riscv64-oe-linux/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
make: *** [Makefile:100: clinfo] Error 1
root@root:~/CL/clinfo# 
```

I believe I'm just missing some linking libs to configure before making clinfo, can you please help me out with this issue?

Any help will be greatly appreciated. Thank you!

Regards,
/Ravi Kiran

**Comment by Oblomov** [comment]
You probably need to install the OpenCL library and development files. On most Linux distributions this is a package named something like `ocl-icd-libopencl1` or something similar. The details depend on the operating system you're using, and are beyond the scope of what I can help you with, sorry.

**Comment by iravikiran** [comment]
Hi @Oblomov, Thanks for your reply.. 

I'm on Linux Kernel, and I've Imagination GPU with all their necessary libs and bins available in place, I really understand its beyond you're scope, but if you can suggest me here it'll be really helpful to fix this issue. 

Also can you please help me which all path needs to be exported for the clinfo to identify the dependencies.? Kindly help me on this. Thank you!  

Reagrds,
Ravi Kiran

**Comment by iravikiran** [comment]
> You probably need to install the OpenCL library and development files. On most Linux distributions this is a package named something like `ocl-icd-libopencl1` or something similar. The details depend on the operating system you're using, and are beyond the scope of what I can help you with, sorry.

Thanks for your suggestions, there was an issue with ICD Loaders, but it's resolved now.. Thanks for your help.
