### ISSUE TITLE
libOpenCL.so.1: no version information available (required by ./clinfo)

### ISSUE THREAD

**Issue by iravikiran** [Oblomov/clinfo#97]
Hello Oblomov, 

When trying to execute the compiled clinfo application, I see a message as below, although clinfo is successfully able to provide my GPU details and various information properly without any problems.

`./clinfo: /usr/lib/libOpenCL.so.1: no version information available (required by ./clinfo)`

Though there is `libOpenCL.so.1` file available in the `/usr/lib` directory and all the details provided by `clinfo` are right, I'm not sure of why the above error message is logged, can you please help me on this to how we can resolve this issue? 

Appreciate any support or help on this issue, Thank you!

Regards,
Ravi Kiran

**Comment by iravikiran** [comment]
Hello Team, Any insights on this? 

Regards,
/Ravi

**Comment by Oblomov** [comment]
Sorry, I have no idea why you get this error. It's possible you have multiple libOpenCL installed in your system and the one you liked at build time has a different library version compared to the one found at runtime, which is usually the reason for the error `no version information available`.

I'm closing this as it doesn't seem to be an issue with `clinfo` itself.
