### ISSUE TITLE
Nothing returned

### ISSUE THREAD

**Issue by ilovesusu** [Oblomov/clinfo#98]
`sudo clinfo --list` 

no output

**Comment by Oblomov** [comment]
No output generally means that no platforms are available (`clinfo` without command-line options would then report `Number of platforms: 0`). I'm closing this for the time being. If you do find that this is actually a `clinfo` issue (e.g. other programs see OpenCL platforms and devices, while clinfo doesn't), feel free to reopen with additional details (O.S. platforms installed, etc)
